/* automatically generated by rust-bindgen */

#![allow(non_snake_case, non_camel_case_types, non_upper_case_globals, unused)]use libc::*;
type __be16 = u16;
type __be32 = u32;
type __be64 = u64;

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::core::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::core::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        ::core::slice::from_raw_parts(self.as_ptr(), len)
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        ::core::slice::from_raw_parts_mut(self.as_mut_ptr(), len)
    }
}
impl<T> ::core::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const __BITS_PER_LONG: u32 = 64;
pub const __FD_SETSIZE: u32 = 1024;
pub const CN_IDX_PROC: u32 = 1;
pub const CN_VAL_PROC: u32 = 1;
pub const CN_IDX_CIFS: u32 = 2;
pub const CN_VAL_CIFS: u32 = 1;
pub const CN_W1_IDX: u32 = 3;
pub const CN_W1_VAL: u32 = 1;
pub const CN_IDX_V86D: u32 = 4;
pub const CN_VAL_V86D_UVESAFB: u32 = 1;
pub const CN_IDX_BB: u32 = 5;
pub const CN_DST_IDX: u32 = 6;
pub const CN_DST_VAL: u32 = 1;
pub const CN_IDX_DM: u32 = 7;
pub const CN_VAL_DM_USERSPACE_LOG: u32 = 1;
pub const CN_IDX_DRBD: u32 = 8;
pub const CN_VAL_DRBD: u32 = 1;
pub const CN_KVP_IDX: u32 = 9;
pub const CN_KVP_VAL: u32 = 1;
pub const CN_VSS_IDX: u32 = 10;
pub const CN_VSS_VAL: u32 = 1;
pub const CN_NETLINK_USERS: u32 = 11;
pub const CONNECTOR_MAX_MSG_SIZE: u32 = 16384;
pub const SI_LOAD_SHIFT: u32 = 16;
pub const _K_SS_MAXSIZE: u32 = 128;
pub const NETLINK_ROUTE: u32 = 0;
pub const NETLINK_UNUSED: u32 = 1;
pub const NETLINK_USERSOCK: u32 = 2;
pub const NETLINK_FIREWALL: u32 = 3;
pub const NETLINK_SOCK_DIAG: u32 = 4;
pub const NETLINK_NFLOG: u32 = 5;
pub const NETLINK_XFRM: u32 = 6;
pub const NETLINK_SELINUX: u32 = 7;
pub const NETLINK_ISCSI: u32 = 8;
pub const NETLINK_AUDIT: u32 = 9;
pub const NETLINK_FIB_LOOKUP: u32 = 10;
pub const NETLINK_CONNECTOR: u32 = 11;
pub const NETLINK_NETFILTER: u32 = 12;
pub const NETLINK_IP6_FW: u32 = 13;
pub const NETLINK_DNRTMSG: u32 = 14;
pub const NETLINK_KOBJECT_UEVENT: u32 = 15;
pub const NETLINK_GENERIC: u32 = 16;
pub const NETLINK_SCSITRANSPORT: u32 = 18;
pub const NETLINK_ECRYPTFS: u32 = 19;
pub const NETLINK_RDMA: u32 = 20;
pub const NETLINK_CRYPTO: u32 = 21;
pub const NETLINK_SMC: u32 = 22;
pub const NETLINK_INET_DIAG: u32 = 4;
pub const MAX_LINKS: u32 = 32;
pub const NLM_F_REQUEST: u32 = 1;
pub const NLM_F_MULTI: u32 = 2;
pub const NLM_F_ACK: u32 = 4;
pub const NLM_F_ECHO: u32 = 8;
pub const NLM_F_DUMP_INTR: u32 = 16;
pub const NLM_F_DUMP_FILTERED: u32 = 32;
pub const NLM_F_ROOT: u32 = 256;
pub const NLM_F_MATCH: u32 = 512;
pub const NLM_F_ATOMIC: u32 = 1024;
pub const NLM_F_DUMP: u32 = 768;
pub const NLM_F_REPLACE: u32 = 256;
pub const NLM_F_EXCL: u32 = 512;
pub const NLM_F_CREATE: u32 = 1024;
pub const NLM_F_APPEND: u32 = 2048;
pub const NLM_F_NONREC: u32 = 256;
pub const NLM_F_CAPPED: u32 = 256;
pub const NLM_F_ACK_TLVS: u32 = 512;
pub const NLMSG_ALIGNTO: u32 = 4;
pub const NLMSG_NOOP: u32 = 1;
pub const NLMSG_ERROR: u32 = 2;
pub const NLMSG_DONE: u32 = 3;
pub const NLMSG_OVERRUN: u32 = 4;
pub const NLMSG_MIN_TYPE: u32 = 16;
pub const NETLINK_ADD_MEMBERSHIP: u32 = 1;
pub const NETLINK_DROP_MEMBERSHIP: u32 = 2;
pub const NETLINK_PKTINFO: u32 = 3;
pub const NETLINK_BROADCAST_ERROR: u32 = 4;
pub const NETLINK_NO_ENOBUFS: u32 = 5;
pub const NETLINK_RX_RING: u32 = 6;
pub const NETLINK_TX_RING: u32 = 7;
pub const NETLINK_LISTEN_ALL_NSID: u32 = 8;
pub const NETLINK_LIST_MEMBERSHIPS: u32 = 9;
pub const NETLINK_CAP_ACK: u32 = 10;
pub const NETLINK_EXT_ACK: u32 = 11;
pub const NETLINK_GET_STRICT_CHK: u32 = 12;
pub const NL_MMAP_MSG_ALIGNMENT: u32 = 4;
pub const NET_MAJOR: u32 = 36;
pub const NLA_F_NESTED: u32 = 32768;
pub const NLA_F_NET_BYTEORDER: u32 = 16384;
pub const NLA_TYPE_MASK: i32 = -49153;
pub const NLA_ALIGNTO: u32 = 4;
pub type __s8 = libc::c_schar;
pub type __u8 = libc::c_uchar;
pub type __s16 = libc::c_short;
pub type __u16 = libc::c_ushort;
pub type __s32 = libc::c_int;
pub type __u32 = libc::c_uint;
pub type __s64 = libc::c_longlong;
pub type __u64 = libc::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fd_set {
    pub fds_bits: [libc::c_ulong; 16usize],
}
#[test]
fn bindgen_test_layout___kernel_fd_set() {
    assert_eq!(
        ::core::mem::size_of::<__kernel_fd_set>(),
        128usize,
        concat!("Size of: ", stringify!(__kernel_fd_set))
    );
    assert_eq!(
        ::core::mem::align_of::<__kernel_fd_set>(),
        8usize,
        concat!("Alignment of ", stringify!(__kernel_fd_set))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<__kernel_fd_set>())).fds_bits as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_fd_set),
            "::",
            stringify!(fds_bits)
        )
    );
}
pub type __kernel_sighandler_t = ::core::option::Option<unsafe extern "C" fn(arg1: libc::c_int)>;
pub type __kernel_key_t = libc::c_int;
pub type __kernel_mqd_t = libc::c_int;
pub type __kernel_old_uid_t = libc::c_ushort;
pub type __kernel_old_gid_t = libc::c_ushort;
pub type __kernel_old_dev_t = libc::c_ulong;
pub type __kernel_long_t = libc::c_long;
pub type __kernel_ulong_t = libc::c_ulong;
pub type __kernel_ino_t = __kernel_ulong_t;
pub type __kernel_mode_t = libc::c_uint;
pub type __kernel_pid_t = libc::c_int;
pub type __kernel_ipc_pid_t = libc::c_int;
pub type __kernel_uid_t = libc::c_uint;
pub type __kernel_gid_t = libc::c_uint;
pub type __kernel_suseconds_t = __kernel_long_t;
pub type __kernel_daddr_t = libc::c_int;
pub type __kernel_uid32_t = libc::c_uint;
pub type __kernel_gid32_t = libc::c_uint;
pub type __kernel_size_t = __kernel_ulong_t;
pub type __kernel_ssize_t = __kernel_long_t;
pub type __kernel_ptrdiff_t = __kernel_long_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __kernel_fsid_t {
    pub val: [libc::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___kernel_fsid_t() {
    assert_eq!(
        ::core::mem::size_of::<__kernel_fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__kernel_fsid_t))
    );
    assert_eq!(
        ::core::mem::align_of::<__kernel_fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__kernel_fsid_t))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<__kernel_fsid_t>())).val as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_fsid_t),
            "::",
            stringify!(val)
        )
    );
}
pub type __kernel_off_t = __kernel_long_t;
pub type __kernel_loff_t = libc::c_longlong;
pub type __kernel_time_t = __kernel_long_t;
pub type __kernel_time64_t = libc::c_longlong;
pub type __kernel_clock_t = __kernel_long_t;
pub type __kernel_timer_t = libc::c_int;
pub type __kernel_clockid_t = libc::c_int;
pub type __kernel_caddr_t = *mut libc::c_char;
pub type __kernel_uid16_t = libc::c_ushort;
pub type __kernel_gid16_t = libc::c_ushort;
pub type __le16 = __u16;
pub type __le32 = __u32;
pub type __le64 = __u64;
pub type __sum16 = __u16;
pub type __wsum = __u32;
pub type __poll_t = libc::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cb_id {
    pub idx: __u32,
    pub val: __u32,
}
#[test]
fn bindgen_test_layout_cb_id() {
    assert_eq!(
        ::core::mem::size_of::<cb_id>(),
        8usize,
        concat!("Size of: ", stringify!(cb_id))
    );
    assert_eq!(
        ::core::mem::align_of::<cb_id>(),
        4usize,
        concat!("Alignment of ", stringify!(cb_id))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cb_id>())).idx as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(cb_id),
            "::",
            stringify!(idx)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cb_id>())).val as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(cb_id),
            "::",
            stringify!(val)
        )
    );
}
#[repr(C)]
#[derive(Debug)]
pub struct cn_msg {
    pub id: cb_id,
    pub seq: __u32,
    pub ack: __u32,
    pub len: __u16,
    pub flags: __u16,
    pub data: __IncompleteArrayField<__u8>,
}
#[test]
fn bindgen_test_layout_cn_msg() {
    assert_eq!(
        ::core::mem::size_of::<cn_msg>(),
        20usize,
        concat!("Size of: ", stringify!(cn_msg))
    );
    assert_eq!(
        ::core::mem::align_of::<cn_msg>(),
        4usize,
        concat!("Alignment of ", stringify!(cn_msg))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cn_msg>())).id as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(cn_msg),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cn_msg>())).seq as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(cn_msg),
            "::",
            stringify!(seq)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cn_msg>())).ack as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(cn_msg),
            "::",
            stringify!(ack)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cn_msg>())).len as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(cn_msg),
            "::",
            stringify!(len)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cn_msg>())).flags as *const _ as usize },
        18usize,
        concat!(
            "Offset of field: ",
            stringify!(cn_msg),
            "::",
            stringify!(flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<cn_msg>())).data as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(cn_msg),
            "::",
            stringify!(data)
        )
    );
}
#[repr(C)]
#[derive(Debug)]
pub struct sysinfo {
    pub uptime: __kernel_long_t,
    pub loads: [__kernel_ulong_t; 3usize],
    pub totalram: __kernel_ulong_t,
    pub freeram: __kernel_ulong_t,
    pub sharedram: __kernel_ulong_t,
    pub bufferram: __kernel_ulong_t,
    pub totalswap: __kernel_ulong_t,
    pub freeswap: __kernel_ulong_t,
    pub procs: __u16,
    pub pad: __u16,
    pub totalhigh: __kernel_ulong_t,
    pub freehigh: __kernel_ulong_t,
    pub mem_unit: __u32,
    pub _f: __IncompleteArrayField<libc::c_char>,
}
#[test]
fn bindgen_test_layout_sysinfo() {
    assert_eq!(
        ::core::mem::size_of::<sysinfo>(),
        112usize,
        concat!("Size of: ", stringify!(sysinfo))
    );
    assert_eq!(
        ::core::mem::align_of::<sysinfo>(),
        8usize,
        concat!("Alignment of ", stringify!(sysinfo))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).uptime as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(uptime)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).loads as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(loads)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).totalram as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(totalram)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).freeram as *const _ as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(freeram)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).sharedram as *const _ as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(sharedram)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).bufferram as *const _ as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(bufferram)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).totalswap as *const _ as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(totalswap)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).freeswap as *const _ as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(freeswap)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).procs as *const _ as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(procs)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).pad as *const _ as usize },
        82usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(pad)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).totalhigh as *const _ as usize },
        88usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(totalhigh)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).freehigh as *const _ as usize },
        96usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(freehigh)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>())).mem_unit as *const _ as usize },
        104usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(mem_unit)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sysinfo>()))._f as *const _ as usize },
        108usize,
        concat!(
            "Offset of field: ",
            stringify!(sysinfo),
            "::",
            stringify!(_f)
        )
    );
}
pub type __kernel_sa_family_t = libc::c_ushort;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __kernel_sockaddr_storage {
    pub __bindgen_anon_1: __kernel_sockaddr_storage__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union __kernel_sockaddr_storage__bindgen_ty_1 {
    pub __bindgen_anon_1: __kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1,
    pub __align: *mut libc::c_void,
    _bindgen_union_align: [u64; 16usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct __kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1 {
    pub ss_family: __kernel_sa_family_t,
    pub __data: [libc::c_char; 126usize],
}
#[test]
fn bindgen_test_layout___kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1() {
    assert_eq!(
        ::core::mem::size_of::<__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1>(),
        128usize,
        concat!(
            "Size of: ",
            stringify!(__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1>(),
        2usize,
        concat!(
            "Alignment of ",
            stringify!(__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1>()))
                .ss_family as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1),
            "::",
            stringify!(ss_family)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1>()))
                .__data as *const _ as usize
        },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_sockaddr_storage__bindgen_ty_1__bindgen_ty_1),
            "::",
            stringify!(__data)
        )
    );
}
#[test]
fn bindgen_test_layout___kernel_sockaddr_storage__bindgen_ty_1() {
    assert_eq!(
        ::core::mem::size_of::<__kernel_sockaddr_storage__bindgen_ty_1>(),
        128usize,
        concat!(
            "Size of: ",
            stringify!(__kernel_sockaddr_storage__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<__kernel_sockaddr_storage__bindgen_ty_1>(),
        8usize,
        concat!(
            "Alignment of ",
            stringify!(__kernel_sockaddr_storage__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<__kernel_sockaddr_storage__bindgen_ty_1>())).__align as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__kernel_sockaddr_storage__bindgen_ty_1),
            "::",
            stringify!(__align)
        )
    );
}
#[test]
fn bindgen_test_layout___kernel_sockaddr_storage() {
    assert_eq!(
        ::core::mem::size_of::<__kernel_sockaddr_storage>(),
        128usize,
        concat!("Size of: ", stringify!(__kernel_sockaddr_storage))
    );
    assert_eq!(
        ::core::mem::align_of::<__kernel_sockaddr_storage>(),
        8usize,
        concat!("Alignment of ", stringify!(__kernel_sockaddr_storage))
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sockaddr_nl {
    pub nl_family: __kernel_sa_family_t,
    pub nl_pad: libc::c_ushort,
    pub nl_pid: __u32,
    pub nl_groups: __u32,
}
#[test]
fn bindgen_test_layout_sockaddr_nl() {
    assert_eq!(
        ::core::mem::size_of::<sockaddr_nl>(),
        12usize,
        concat!("Size of: ", stringify!(sockaddr_nl))
    );
    assert_eq!(
        ::core::mem::align_of::<sockaddr_nl>(),
        4usize,
        concat!("Alignment of ", stringify!(sockaddr_nl))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sockaddr_nl>())).nl_family as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(sockaddr_nl),
            "::",
            stringify!(nl_family)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sockaddr_nl>())).nl_pad as *const _ as usize },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(sockaddr_nl),
            "::",
            stringify!(nl_pad)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sockaddr_nl>())).nl_pid as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(sockaddr_nl),
            "::",
            stringify!(nl_pid)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<sockaddr_nl>())).nl_groups as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(sockaddr_nl),
            "::",
            stringify!(nl_groups)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nlmsghdr {
    pub nlmsg_len: __u32,
    pub nlmsg_type: __u16,
    pub nlmsg_flags: __u16,
    pub nlmsg_seq: __u32,
    pub nlmsg_pid: __u32,
}
#[test]
fn bindgen_test_layout_nlmsghdr() {
    assert_eq!(
        ::core::mem::size_of::<nlmsghdr>(),
        16usize,
        concat!("Size of: ", stringify!(nlmsghdr))
    );
    assert_eq!(
        ::core::mem::align_of::<nlmsghdr>(),
        4usize,
        concat!("Alignment of ", stringify!(nlmsghdr))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlmsghdr>())).nlmsg_len as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nlmsghdr),
            "::",
            stringify!(nlmsg_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlmsghdr>())).nlmsg_type as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(nlmsghdr),
            "::",
            stringify!(nlmsg_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlmsghdr>())).nlmsg_flags as *const _ as usize },
        6usize,
        concat!(
            "Offset of field: ",
            stringify!(nlmsghdr),
            "::",
            stringify!(nlmsg_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlmsghdr>())).nlmsg_seq as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(nlmsghdr),
            "::",
            stringify!(nlmsg_seq)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlmsghdr>())).nlmsg_pid as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(nlmsghdr),
            "::",
            stringify!(nlmsg_pid)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nlmsgerr {
    pub error: libc::c_int,
    pub msg: nlmsghdr,
}
#[test]
fn bindgen_test_layout_nlmsgerr() {
    assert_eq!(
        ::core::mem::size_of::<nlmsgerr>(),
        20usize,
        concat!("Size of: ", stringify!(nlmsgerr))
    );
    assert_eq!(
        ::core::mem::align_of::<nlmsgerr>(),
        4usize,
        concat!("Alignment of ", stringify!(nlmsgerr))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlmsgerr>())).error as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nlmsgerr),
            "::",
            stringify!(error)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlmsgerr>())).msg as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(nlmsgerr),
            "::",
            stringify!(msg)
        )
    );
}
pub const NLMSGERR_ATTR_UNUSED: nlmsgerr_attrs = 0;
pub const NLMSGERR_ATTR_MSG: nlmsgerr_attrs = 1;
pub const NLMSGERR_ATTR_OFFS: nlmsgerr_attrs = 2;
pub const NLMSGERR_ATTR_COOKIE: nlmsgerr_attrs = 3;
pub const __NLMSGERR_ATTR_MAX: nlmsgerr_attrs = 4;
pub const NLMSGERR_ATTR_MAX: nlmsgerr_attrs = 3;
pub type nlmsgerr_attrs = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nl_pktinfo {
    pub group: __u32,
}
#[test]
fn bindgen_test_layout_nl_pktinfo() {
    assert_eq!(
        ::core::mem::size_of::<nl_pktinfo>(),
        4usize,
        concat!("Size of: ", stringify!(nl_pktinfo))
    );
    assert_eq!(
        ::core::mem::align_of::<nl_pktinfo>(),
        4usize,
        concat!("Alignment of ", stringify!(nl_pktinfo))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_pktinfo>())).group as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_pktinfo),
            "::",
            stringify!(group)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nl_mmap_req {
    pub nm_block_size: libc::c_uint,
    pub nm_block_nr: libc::c_uint,
    pub nm_frame_size: libc::c_uint,
    pub nm_frame_nr: libc::c_uint,
}
#[test]
fn bindgen_test_layout_nl_mmap_req() {
    assert_eq!(
        ::core::mem::size_of::<nl_mmap_req>(),
        16usize,
        concat!("Size of: ", stringify!(nl_mmap_req))
    );
    assert_eq!(
        ::core::mem::align_of::<nl_mmap_req>(),
        4usize,
        concat!("Alignment of ", stringify!(nl_mmap_req))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_req>())).nm_block_size as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_req),
            "::",
            stringify!(nm_block_size)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_req>())).nm_block_nr as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_req),
            "::",
            stringify!(nm_block_nr)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_req>())).nm_frame_size as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_req),
            "::",
            stringify!(nm_frame_size)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_req>())).nm_frame_nr as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_req),
            "::",
            stringify!(nm_frame_nr)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nl_mmap_hdr {
    pub nm_status: libc::c_uint,
    pub nm_len: libc::c_uint,
    pub nm_group: __u32,
    pub nm_pid: __u32,
    pub nm_uid: __u32,
    pub nm_gid: __u32,
}
#[test]
fn bindgen_test_layout_nl_mmap_hdr() {
    assert_eq!(
        ::core::mem::size_of::<nl_mmap_hdr>(),
        24usize,
        concat!("Size of: ", stringify!(nl_mmap_hdr))
    );
    assert_eq!(
        ::core::mem::align_of::<nl_mmap_hdr>(),
        4usize,
        concat!("Alignment of ", stringify!(nl_mmap_hdr))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_hdr>())).nm_status as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_hdr),
            "::",
            stringify!(nm_status)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_hdr>())).nm_len as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_hdr),
            "::",
            stringify!(nm_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_hdr>())).nm_group as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_hdr),
            "::",
            stringify!(nm_group)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_hdr>())).nm_pid as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_hdr),
            "::",
            stringify!(nm_pid)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_hdr>())).nm_uid as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_hdr),
            "::",
            stringify!(nm_uid)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nl_mmap_hdr>())).nm_gid as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(nl_mmap_hdr),
            "::",
            stringify!(nm_gid)
        )
    );
}
pub const NL_MMAP_STATUS_UNUSED: nl_mmap_status = 0;
pub const NL_MMAP_STATUS_RESERVED: nl_mmap_status = 1;
pub const NL_MMAP_STATUS_VALID: nl_mmap_status = 2;
pub const NL_MMAP_STATUS_COPY: nl_mmap_status = 3;
pub const NL_MMAP_STATUS_SKIP: nl_mmap_status = 4;
pub type nl_mmap_status = u32;
pub const NETLINK_UNCONNECTED: _bindgen_ty_1 = 0;
pub const NETLINK_CONNECTED: _bindgen_ty_1 = 1;
pub type _bindgen_ty_1 = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nlattr {
    pub nla_len: __u16,
    pub nla_type: __u16,
}
#[test]
fn bindgen_test_layout_nlattr() {
    assert_eq!(
        ::core::mem::size_of::<nlattr>(),
        4usize,
        concat!("Size of: ", stringify!(nlattr))
    );
    assert_eq!(
        ::core::mem::align_of::<nlattr>(),
        2usize,
        concat!("Alignment of ", stringify!(nlattr))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlattr>())).nla_len as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nlattr),
            "::",
            stringify!(nla_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nlattr>())).nla_type as *const _ as usize },
        2usize,
        concat!(
            "Offset of field: ",
            stringify!(nlattr),
            "::",
            stringify!(nla_type)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nla_bitfield32 {
    pub value: __u32,
    pub selector: __u32,
}
#[test]
fn bindgen_test_layout_nla_bitfield32() {
    assert_eq!(
        ::core::mem::size_of::<nla_bitfield32>(),
        8usize,
        concat!("Size of: ", stringify!(nla_bitfield32))
    );
    assert_eq!(
        ::core::mem::align_of::<nla_bitfield32>(),
        4usize,
        concat!("Alignment of ", stringify!(nla_bitfield32))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nla_bitfield32>())).value as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(nla_bitfield32),
            "::",
            stringify!(value)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<nla_bitfield32>())).selector as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(nla_bitfield32),
            "::",
            stringify!(selector)
        )
    );
}
pub const PROC_CN_MCAST_LISTEN: proc_cn_mcast_op = 1;
pub const PROC_CN_MCAST_IGNORE: proc_cn_mcast_op = 2;
pub type proc_cn_mcast_op = u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event {
    pub what: proc_event_what,
    pub cpu: __u32,
    pub timestamp_ns: __u64,
    pub event_data: proc_event__bindgen_ty_1,
}
pub const PROC_EVENT_NONE: proc_event_what = 0;
pub const PROC_EVENT_FORK: proc_event_what = 1;
pub const PROC_EVENT_EXEC: proc_event_what = 2;
pub const PROC_EVENT_UID: proc_event_what = 4;
pub const PROC_EVENT_GID: proc_event_what = 64;
pub const PROC_EVENT_SID: proc_event_what = 128;
pub const PROC_EVENT_PTRACE: proc_event_what = 256;
pub const PROC_EVENT_COMM: proc_event_what = 512;
pub const PROC_EVENT_COREDUMP: proc_event_what = 1073741824;
pub const PROC_EVENT_EXIT: proc_event_what = 2147483648;
pub type proc_event_what = u32;
#[repr(C)]
#[derive(Copy, Clone)]
pub union proc_event__bindgen_ty_1 {
    pub ack: proc_event__bindgen_ty_1__bindgen_ty_1,
    pub fork: proc_event__bindgen_ty_1_fork_proc_event,
    pub exec: proc_event__bindgen_ty_1_exec_proc_event,
    pub id: proc_event__bindgen_ty_1_id_proc_event,
    pub sid: proc_event__bindgen_ty_1_sid_proc_event,
    pub ptrace: proc_event__bindgen_ty_1_ptrace_proc_event,
    pub comm: proc_event__bindgen_ty_1_comm_proc_event,
    pub coredump: proc_event__bindgen_ty_1_coredump_proc_event,
    pub exit: proc_event__bindgen_ty_1_exit_proc_event,
    _bindgen_union_align: [u32; 6usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1__bindgen_ty_1 {
    pub err: __u32,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1__bindgen_ty_1() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1__bindgen_ty_1>(),
        4usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1__bindgen_ty_1>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1__bindgen_ty_1>())).err as *const _
                as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1__bindgen_ty_1),
            "::",
            stringify!(err)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1_fork_proc_event {
    pub parent_pid: __kernel_pid_t,
    pub parent_tgid: __kernel_pid_t,
    pub child_pid: __kernel_pid_t,
    pub child_tgid: __kernel_pid_t,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_fork_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_fork_proc_event>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_fork_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_fork_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_fork_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_fork_proc_event>())).parent_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_fork_proc_event),
            "::",
            stringify!(parent_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_fork_proc_event>())).parent_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_fork_proc_event),
            "::",
            stringify!(parent_tgid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_fork_proc_event>())).child_pid
                as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_fork_proc_event),
            "::",
            stringify!(child_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_fork_proc_event>())).child_tgid
                as *const _ as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_fork_proc_event),
            "::",
            stringify!(child_tgid)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1_exec_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_exec_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_exec_proc_event>(),
        8usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_exec_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_exec_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_exec_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exec_proc_event>())).process_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exec_proc_event),
            "::",
            stringify!(process_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exec_proc_event>())).process_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exec_proc_event),
            "::",
            stringify!(process_tgid)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct proc_event__bindgen_ty_1_id_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub r: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1,
    pub e: proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1 {
    pub ruid: __u32,
    pub rgid: __u32,
    _bindgen_union_align: u32,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1>(),
        4usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1>())).ruid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1),
            "::",
            stringify!(ruid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1>())).rgid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_1),
            "::",
            stringify!(rgid)
        )
    );
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2 {
    pub euid: __u32,
    pub egid: __u32,
    _bindgen_union_align: u32,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2>(),
        4usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2>())).euid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2),
            "::",
            stringify!(euid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2>())).egid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event__bindgen_ty_2),
            "::",
            stringify!(egid)
        )
    );
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_id_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_id_proc_event>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_id_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event>())).process_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event),
            "::",
            stringify!(process_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event>())).process_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event),
            "::",
            stringify!(process_tgid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event>())).r as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event),
            "::",
            stringify!(r)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_id_proc_event>())).e as *const _
                as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_id_proc_event),
            "::",
            stringify!(e)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1_sid_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_sid_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_sid_proc_event>(),
        8usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_sid_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_sid_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_sid_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_sid_proc_event>())).process_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_sid_proc_event),
            "::",
            stringify!(process_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_sid_proc_event>())).process_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_sid_proc_event),
            "::",
            stringify!(process_tgid)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1_ptrace_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub tracer_pid: __kernel_pid_t,
    pub tracer_tgid: __kernel_pid_t,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_ptrace_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_ptrace_proc_event>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_ptrace_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_ptrace_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_ptrace_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_ptrace_proc_event>())).process_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_ptrace_proc_event),
            "::",
            stringify!(process_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_ptrace_proc_event>())).process_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_ptrace_proc_event),
            "::",
            stringify!(process_tgid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_ptrace_proc_event>())).tracer_pid
                as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_ptrace_proc_event),
            "::",
            stringify!(tracer_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_ptrace_proc_event>())).tracer_tgid
                as *const _ as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_ptrace_proc_event),
            "::",
            stringify!(tracer_tgid)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1_comm_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub comm: [libc::c_char; 16usize],
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_comm_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_comm_proc_event>(),
        24usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_comm_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_comm_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_comm_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_comm_proc_event>())).process_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_comm_proc_event),
            "::",
            stringify!(process_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_comm_proc_event>())).process_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_comm_proc_event),
            "::",
            stringify!(process_tgid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_comm_proc_event>())).comm as *const _
                as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_comm_proc_event),
            "::",
            stringify!(comm)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1_coredump_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub parent_pid: __kernel_pid_t,
    pub parent_tgid: __kernel_pid_t,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_coredump_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_coredump_proc_event>(),
        16usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_coredump_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_coredump_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_coredump_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_coredump_proc_event>())).process_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_coredump_proc_event),
            "::",
            stringify!(process_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_coredump_proc_event>())).process_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_coredump_proc_event),
            "::",
            stringify!(process_tgid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_coredump_proc_event>())).parent_pid
                as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_coredump_proc_event),
            "::",
            stringify!(parent_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_coredump_proc_event>())).parent_tgid
                as *const _ as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_coredump_proc_event),
            "::",
            stringify!(parent_tgid)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct proc_event__bindgen_ty_1_exit_proc_event {
    pub process_pid: __kernel_pid_t,
    pub process_tgid: __kernel_pid_t,
    pub exit_code: __u32,
    pub exit_signal: __u32,
    pub parent_pid: __kernel_pid_t,
    pub parent_tgid: __kernel_pid_t,
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1_exit_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1_exit_proc_event>(),
        24usize,
        concat!(
            "Size of: ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event)
        )
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1_exit_proc_event>(),
        4usize,
        concat!(
            "Alignment of ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exit_proc_event>())).process_pid
                as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event),
            "::",
            stringify!(process_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exit_proc_event>())).process_tgid
                as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event),
            "::",
            stringify!(process_tgid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exit_proc_event>())).exit_code
                as *const _ as usize
        },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event),
            "::",
            stringify!(exit_code)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exit_proc_event>())).exit_signal
                as *const _ as usize
        },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event),
            "::",
            stringify!(exit_signal)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exit_proc_event>())).parent_pid
                as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event),
            "::",
            stringify!(parent_pid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1_exit_proc_event>())).parent_tgid
                as *const _ as usize
        },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1_exit_proc_event),
            "::",
            stringify!(parent_tgid)
        )
    );
}
#[test]
fn bindgen_test_layout_proc_event__bindgen_ty_1() {
    assert_eq!(
        ::core::mem::size_of::<proc_event__bindgen_ty_1>(),
        24usize,
        concat!("Size of: ", stringify!(proc_event__bindgen_ty_1))
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event__bindgen_ty_1>(),
        4usize,
        concat!("Alignment of ", stringify!(proc_event__bindgen_ty_1))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).ack as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(ack)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).fork as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(fork)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).exec as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(exec)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).id as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(id)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).sid as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(sid)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).ptrace as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(ptrace)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).comm as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(comm)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).coredump as *const _ as usize
        },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(coredump)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event__bindgen_ty_1>())).exit as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event__bindgen_ty_1),
            "::",
            stringify!(exit)
        )
    );
}
#[test]
fn bindgen_test_layout_proc_event() {
    assert_eq!(
        ::core::mem::size_of::<proc_event>(),
        40usize,
        concat!("Size of: ", stringify!(proc_event))
    );
    assert_eq!(
        ::core::mem::align_of::<proc_event>(),
        8usize,
        concat!("Alignment of ", stringify!(proc_event))
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event>())).what as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event),
            "::",
            stringify!(what)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event>())).cpu as *const _ as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event),
            "::",
            stringify!(cpu)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event>())).timestamp_ns as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event),
            "::",
            stringify!(timestamp_ns)
        )
    );
    assert_eq!(
        unsafe { &(*(::core::ptr::null::<proc_event>())).event_data as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(proc_event),
            "::",
            stringify!(event_data)
        )
    );
}
